# 3.10 Numpyとの相互運用性

In [1]:
import torch

In [6]:
points = torch.ones(3, 4)
points_up = points.numpy()
print(points_up)
print(type(points_up))

print(points.storage())
points_up[0] = 100
print(points.storage())

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]
 100.0
 100.0
 100.0
 100.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 12]


# メモ
テンソルをNumpyに変換したものはテンソルのストレージと同じバッファストレージを共有している