# 第３章 演習問題

In [3]:
import torch

## 問1

In [6]:
li = list(range(9))
a = torch.tensor(li)

# (a)
b = a.view(3, 3)
print(b)

# (b)
c = b[1:, 1:]
print(c)
print(c.size())
print(c.storage_offset())
print(c.stride())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)


## 問2

In [8]:
cosine_values = torch.cos(a)
print(cosine_values)

sqrt_values = torch.sqrt(a)
print(sqrt_values)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])
