# テンソルのメタ情報(サイズ、オフセット、ストライド)
* サイズ: テンソルの各次元を表すタプル
* オフセット: テンソルの最初の要素に対応するストレージ内のインデックス
* ストライド: テンソルの次元に沿って次の要素に移動するために必要なメモリ上のステップ数
  * 1次元テンソル（ベクトル）の場合、ストライドは通常1です。つまり、隣接する要素にアクセスするためには1ステップ移動する必要があります。
  * 2次元テンソル（行列）では、ストライドは2つの数値で表されます。1つ目の数値は行間のストライド、2つ目の数値は列間のストライド

In [1]:
import torch

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [6]:
points.stride()

(3, 1)

In [11]:
second_point = points[1]
print(second_point.size())

print(second_point.storage_offset())

print(second_point.stride())

torch.Size([2])
2
(1,)


## tensorはNumpyのように参照を保持する

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)

second_point = points[1]
second_point[0] = 100

print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[  4.,   1.],
        [100.,   3.],
        [  2.,   1.]])


# テンソルのクローン(参照を共有せず新しいテンソルを新規作成する)

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)

second_point = points[1].clone()
second_point[0] = 100

print(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


## テンソルの転置(次元の入れ替え)
**ストレージは共有している**

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)

points_t = points.t()
print(points_t)

print(id(points.storage()) == id(points_t.storage()))

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 5., 2.],
        [1., 3., 1.]])
True


## 高次元での転置

In [26]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)

print(some_t.shape)
print(transpose_t.shape)

print(some_t.stride())
print(transpose_t.stride())
print(transpose_t.shape)

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])
(20, 5, 1)
(1, 5, 20)
torch.Size([5, 4, 3])


## テンソルストレージが連続しているか

In [28]:
points.is_contiguous()
points_t.is_contiguous()

False

## 非連続的なテンソルを連続したテンソルに変換

In [36]:
points_t_cont = points_t.contiguous()
print(points_t_cont)
print(points_t.storage())
print(points_t_cont.stride())
print(points_t_cont.storage())

tensor([[4., 5., 2.],
        [1., 3., 1.]])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
(3, 1)
 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
