# 第４章　演習問題

## Question1

### a 各画像を読み込みテンソルに変換

In [64]:
import torch
import imageio
import os
import torchvision.transforms as transforms

dir_path = r'C:\Users\shodai\Desktop\PyTorch_Introduction\data\p1ch4\rgb_test'
resize = transforms.Resize((256, 256))

filenames = [name for name in os.listdir(dir_path)
             if os.path.splitext(name)[-1] == '.png']

batch_size = len(filenames)
batch_t = torch.zeros(batch_size, 3, 256, 256, dtype=torch.float32)

for i, filename in enumerate(filenames):
    img_n = imageio.imread(os.path.join(dir_path, filename))
    img_t = torch.from_numpy(img_n)
    img_t = img_t.permute(2, 0, 1) # (h, w, c)を(c, h, w)に変換
    img_t = resize(img_t) # リサイズ
    img_t = img_t.float()
    batch_t[i] = img_t[:3]

batch_normalization = batch_t / 255.0 # 正規化

print(batch_normalization)
    

torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
torch.Size([4, 256, 256])
tensor([[[[1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          [1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          [1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          ...,
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000],
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000],
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000]],

         [[1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          [1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          [1.0000, 1.0000, 1.0000,  ..., 0.9373, 0.9373, 0.9373],
          ...,
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000],
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000],
          [0.9373, 0.9373, 0.9373,  ..., 1.0000, 1.0000, 1.0000]],

         [[1.0000, 1.0000, 1.0000,  ..., 0.9333, 0.9333, 0.9333],
          [1.0000, 1.0000, 1.0

C:\Users\shodai\AppData\Local\Temp\ipykernel_2548\4227289001.py:16: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_n = imageio.imread(os.path.join(dir_path, filename))
C:\Users\shodai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - 

### b 各画像のテンソルから画像の明るさを求める

In [65]:
import numpy as np
means = torch.zeros(batch_size, 256, 256)

for i, img in enumerate(batch_t):
    m = torch.mean(img, dim=0)
    means[i] = m

print(means.shape)

torch.Size([3, 256, 256])


### c 各画像の各チャンネルの平均を取ってください。求めたチャンネルの平均値だけから、赤、緑、青の物体を識別できるか確認してください。

In [67]:
print(filenames)
for img in batch_t:
    print(img.mean(dim=1).mean(dim=1))

['blue.png', 'green.png', 'red.png']
tensor([136.0672, 184.0344, 227.3976])
tensor([181.8174, 214.0244, 175.6966])
tensor([234.9821, 183.0724, 172.1080])
